name: CI for Mini-Project DNS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install notebook nbconvert

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute MiniProjectDNS.ipynb
      
      - name: Save Output
        run: |
          mkdir -p output
          jupyter nbconvert --to html --execute MiniProjectDNS.ipynb --output-dir=output
      
      - name: Upload Output
        uses: actions/upload-artifact@v4
        with:
          name: notebook-output
          path: output/
